#=================================================
# 测试
#=================================================

name: test scp

on: [push]

env:
  VERSION_1: 1

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: download github files # This would actually build your project, using zip for an example artifact
        run: |
          wget https://github.com/a520ass/Actions-OpenWrt/releases/download/v19.07.2-v2-ath79/my-artifact.zip

      - name: zip files # This would actually build your project, using zip for an example artifact
        run: |
          export scpfilename=my-artifact-`date +"%Y-%m-%d_%H:%M:%S"`.zip
          zip --junk-paths ${scpfilename} tests/*

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ${{ env.scpfilename }}
          target: "/root"