#=================================================
# 测试
#=================================================

name: test scp

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          source: "tests/*"
          target: "/tmp"

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: tests/a.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}